

//login action
export const LOGIN_SUCESS = "LOGIN_SUCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT_USER = "LOGOUT_USER";

//signup action
    
export const SIGNUP_SUCESS = "SIGNUP_SUCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

//user loading
export const USER_LOADED ="USER_LOADED";

//employee action
export const FETCH_EMPLOYEE_SUCESS = "FETCH_EMPLOYEE_SUCESS";
export const FETCH_EMPLOYEE_FAILURE = "FETCH_EMPLOYEE_FAILURE";

export const FETCH_EMPLOYEE_DETAILS_SUCESS = "FETCH_EMPLOYEE_DETAILS_SUCESS";
export const FETCH_EMPLOYEE_DETAILS_FAILURE = "FETCH_EMPLOYEE_DETAILS_FAILURE";

export const UPDATE_EMPLOYEE_DETAILS_SUCCESS = "UPDATE_EMPLOYEE_DETAILS_SUCCESS";
export const UPDATE_EMPLOYEE_DETAILS_FAILURE = "UPDATE_EMPLOYEE_DETAILS_FAILURE";


// menu action
export const FETCH_MENU_BEGIN = "FETCH_MENU_BEGIN";
export const FETCH_MENU_SUCESS = "FETCH_MENU_SUCESS";
export const FETCH_MENU_FAILURE = "FETCH_MENU_FAILURE";

//Adding item to menu

export const ADD_MENU_ITEM_SUCESS = "ADD_MENU_ITEM_SUCESS";
export const ADD_MENU_ITEM_FAILURE=  "ADD_MENU_ITEM_FAILURE";

//update menu item
export const UPDATE_MENU_ITEM_SUCCESS = "UPDATE_MENU_ITEM_SUCCESS";
export const UPDATE_MENU_ITEM_FAILURE = "UPDATE_MENU_ITEM_FAILURE";


//delete menu item
export const DELETE_MENU_ITEM_SUCCESS = "DELETE_MENU_ITEM_SUCCESS";
export const DELETE_MENU_ITEM_FAILURE = "DELETE_MENU_ITEM_FAILURE";
 
