

//login action
export const LOGIN_SUCESS = "LOGIN_SUCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT_USER = "LOGOUT_USER";

//signup action
    
export const SIGNUP_SUCESS = "SIGNUP_SUCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

//user loading
export const USER_LOADED ="USER_LOADED";

//employee action
export const FETCH_EMPLOYEE_SUCESS = "FETCH_EMPLOYEE_SUCESS";
export const FETCH_EMPLOYEE_FAILURE = "FETCH_EMPLOYEE_FAILURE";

export const FETCH_EMPLOYEE_DETAILS_SUCESS = "FETCH_EMPLOYEE_DETAILS_SUCESS";
export const FETCH_EMPLOYEE_DETAILS_FAILURE = "FETCH_EMPLOYEE_DETAILS_FAILURE";

export const UPDATE_EMPLOYEE_DETAILS_SUCCESS = "UPDATE_EMPLOYEE_DETAILS_SUCCESS";
export const UPDATE_EMPLOYEE_DETAILS_FAILURE = "UPDATE_EMPLOYEE_DETAILS_FAILURE";


// menu action
export const FETCH_MENU_BEGIN = "FETCH_MENU_BEGIN";
export const FETCH_MENU_SUCESS = "FETCH_MENU_SUCESS";
export const FETCH_MENU_FAILURE = "FETCH_MENU_FAILURE";

//Adding item to menu

export const ADD_MENU_ITEM_SUCESS = "ADD_MENU_ITEM_SUCESS";
export const ADD_MENU_ITEM_FAILURE=  "ADD_MENU_ITEM_FAILURE";

//update menu item
export const UPDATE_MENU_ITEM_SUCCESS = "UPDATE_MENU_ITEM_SUCCESS";
export const UPDATE_MENU_ITEM_FAILURE = "UPDATE_MENU_ITEM_FAILURE";


//delete menu item
export const DELETE_MENU_ITEM_SUCCESS = "DELETE_MENU_ITEM_SUCCESS";
export const DELETE_MENU_ITEM_FAILURE = "DELETE_MENU_ITEM_FAILURE";


//material action
//fetch material
export const FETCH_MATERIAL_BEGIN = "FETCH_MATERIAL_BEGIN"; 
export const FETCH_MATERIAL_SUCCESS = "FETCH_MATERIAL_SUCCESS";
export const FETCH_MATERIAL_FAILURE="FETCH_MATERIAL_FAILURE";


//add material
export const ADD_MATERIAL_SUCCESS = "ADD_MATERIAL_SUCCESS";
export const ADD_MATERIAL_FAILURE = "ADD_MATERIAL_FAILURE";

//delete maaterial 
export const DELETE_MATERIAL_ITEM_SUCCESS = "DELETE_MATERIAL_ITEM_SUCCESS";
export const DELETE_MATERIAL_ITEM_FAILURE = "DELETE_MATERIAL_ITEM_FAILURE";


//ftech partner 
export const FETCH_PARTNER_BEGIN = "FETCH_PARTNER_BEGIN";
export const FETCH_PARTNER_SUCCESS = "FETCH_PARTNER_SUCCESS";
export const FETCH_PARTNER_FAILURE = "FETCH_PARTNER_FAILURE";

//ADD partner
export const ADD_PARTNER_SUCCESS = "ADD_PARTNER_SUCCESS";
export const ADD_PARTNER_FAILURE =  "FETCH_PARTNER_FAILURE";

//delete partner
export const DELETE_PARTNER_SUCCESS = "DELETE_PARTNER_SUCCESS";
export const DELETE_PARTNER_FAILURE = "DELETE_PARTNER_FAILURE";

//update partner
export const UPDATE_PARTNER_SUCCESS = "UPDATE_PARTNER_SUCCESS";
export const UPDATE_PARTNER_FAILURE = "UPDATE_PARTNER_FAILURE";



 
