

//login action
export const LOGIN_SUCESS = "LOGIN_SUCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";

//signup action
    
export const SIGNUP_SUCESS = "SIGNUP_SUCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

//user loading
export const USER_LOADED ="USER_LOADED";

//employee action
export const FETCH_EMPLOYEE_SUCESS = "FETCH_EMPLOYEE_SUCESS";
export const FETCH_EMPLOYEE_FAILURE = "FETCH_EMPLOYEE_FAILURE";

export const FETCH_EMPLOYEE_DETAILS_SUCESS = "FETCH_EMPLOYEE_DETAILS_SUCESS";
export const FETCH_EMPLOYEE_DETAILS_FAILURE = "FETCH_EMPLOYEE_DETAILS_FAILURE";

export const UPDATE_EMPLOYEE_DETAILS_SUCCESS = "UPDATE_EMPLOYEE_DETAILS_SUCCESS";
export const UPDATE_EMPLOYEE_DETAILS_FAILURE = "UPDATE_EMPLOYEE_DETAILS_FAILURE";

 
